<a href="https://colab.research.google.com/github/kia6279/AI_Summer_of_code/blob/main/Data_analysis_Cleaning_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as ap

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving emdat_dat.xlsx to emdat_dat (3).xlsx

In [ ]:
df = pd.read_excel("emdat_dat.xlsx")

In [ ]:
df

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,1999-9388-DJI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,DJI,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,1999-9388-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SDN,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,1999-9388-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SOM,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,2000-9309-MDG,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,MDG,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm2_code"":154509,""adm2_name"":""Ambatondraza...",2008-01-03,2023-09-25
4,2001-9044-BFA,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,BFA,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":40286,""adm1_name"":""Plateau Centr...",2006-10-26,2023-09-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2022-9784-COD,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,COD,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2022-11-29,2023-09-26
164,2022-9785-MWI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,MWI,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2022-11-29,2023-09-26
165,2022-9786-MLI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,MLI,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2022-11-29,2023-09-26
166,2022-9787-NGA,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,NGA,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2022-11-29,2023-09-26
167,2022-9788-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SDN,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,2022-11-29,2023-09-26

In [ ]:
df.describe()

,Event Name,AID Contribution ('000 US$),Magnitude,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,...,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Entry Date,Last Update
count,0.0,6.000000,4.0,0.0,0.0,0.0,168.000000,133.000000,1.0,168.000000,...,1.560000e+02,0.0,0.0,0.0,0.0,1.100000e+01,1.100000e+01,168.000000,168,168
mean,NaN,20172.000000,225.0,NaN,NaN,NaN,2011.327381,5.451128,1.0,2012.083333,...,2.655667e+06,NaN,NaN,NaN,NaN,5.032727e+05,5.869705e+05,77.019948,2013-06-21 22:51:25.714285824,2023-09-25 02:00:00
min,NaN,417.000000,0.0,NaN,NaN,NaN,2000.000000,1.000000,1.0,2000.000000,...,1.200000e+04,NaN,NaN,NaN,NaN,4.400000e+04,5.432900e+04,58.840648,2005-09-05 00:00:00,2023-09-25 00:00:00
25%,NaN,704.000000,0.0,NaN,NaN,NaN,2005.000000,2.000000,1.0,2006.000000,...,5.135000e+05,NaN,NaN,NaN,NaN,9.950000e+04,1.174685e+05,66.731058,2007-02-14 18:00:00,2023-09-25 00:00:00
50%,NaN,2178.000000,0.0,NaN,NaN,NaN,2011.000000,5.000000,1.0,2012.000000,...,1.425000e+06,NaN,NaN,NaN,NaN,2.500000e+05,3.086850e+05,76.861595,2014-05-05 00:00:00,2023-09-25 00:00:00
75%,NaN,12138.250000,225.0,NaN,NaN,NaN,2017.000000,8.000000,1.0,2018.250000,...,3.325000e+06,NaN,NaN,NaN,NaN,8.165000e+05,8.562340e+05,83.757255,2019-01-18 12:00:00,2023-09-25 00:00:00
max,NaN,100588.000000,900.0,NaN,NaN,NaN,2022.000000,12.000000,1.0,2023.000000,...,2.597281e+07,NaN,NaN,NaN,NaN,1.400000e+06,1.728639e+06,100.000000,2022-11-29 00:00:00,2023-09-26 00:00:00
std,NaN,39798.725271,450.0,NaN,NaN,NaN,6.976004,3.570642,NaN,7.025545,...,3.911632e+06,NaN,NaN,NaN,NaN,4.911607e+05,5.847477e+05,11.666006,NaN,NaN

In [ ]:
df.shape

(168, 46)

In [ ]:
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,1999-9388-DJI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,DJI,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,1999-9388-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SDN,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,1999-9388-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SOM,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,2000-9309-MDG,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,MDG,...,NaN,NaN,NaN,NaN,NaN,NaN,58.840648,"[{""adm2_code"":154509,""adm2_name"":""Ambatondraza...",2008-01-03,2023-09-25
4,2001-9044-BFA,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,BFA,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":40286,""adm1_name"":""Plateau Centr...",2006-10-26,2023-09-25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 46 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     168 non-null    object
 1   Historic                                   168 non-null    object
 2   Classification Key                         168 non-null    object
 3   Disaster Group                             168 non-null    object
 4   Disaster Subgroup                          168 non-null    object
 5   Disaster Type                              168 non-null    object
 6   Disaster Subtype                           168 non-null    object
 7   External IDs                               57 non-null     object
 8   Event Name                                 0 non-null      float64
 9   ISO                                        168 non-null    object
 10  Country                                    168 non-null    object
 11  Subregion                                  168 non-null    object
 12  Region                                     168 non-null    object
 13  Location                                   151 non-null    object
 14  Origin                                     68 non-null     object
 15  Associated Types                           121 non-null    object
 16  OFDA Response                              168 non-null    object
 17  Appeal                                     168 non-null    object
 18  Declaration                                168 non-null    object
 19  AID Contribution ('000 US$)                6 non-null      float64
 20  Magnitude                                  4 non-null      float64
 21  Magnitude Scale                            168 non-null    object
 22  Latitude                                   0 non-null      float64
 23  Longitude                                  0 non-null      float64
 24  River Basin                                0 non-null      float64
 25  Start Year                                 168 non-null    int64
 26  Start Month                                133 non-null    float64
 27  Start Day                                  1 non-null      float64
 28  End Year                                   168 non-null    int64
 29  End Month                                  102 non-null    float64
 30  End Day                                    2 non-null      float64
 31  Total Deaths                               13 non-null     float64
 32  No. Injured                                0 non-null      float64
 33  No. Affected                               156 non-null    float64
 34  No. Homeless                               0 non-null      float64
 35  Total Affected                             156 non-null    float64
 36  Reconstruction Costs ('000 US$)            0 non-null      float64
 37  Reconstruction Costs, Adjusted ('000 US$)  0 non-null      float64
 38  Insured Damage ('000 US$)                  0 non-null      float64
 39  Insured Damage, Adjusted ('000 US$)        0 non-null      float64
 40  Total Damage ('000 US$)                    11 non-null     float64
 41  Total Damage, Adjusted ('000 US$)          11 non-null     float64
 42  CPI                                        168 non-null    float64
 43  Admin Units                                144 non-null    object
 44  Entry Date                                 168 non-null    datetime64[ns]
 45  Last Update                                168 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(22), int64(2), object(20)
memory usage: 60.5+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

DisNo.                                         0
Historic                                       0
Classification Key                             0
Disaster Group                                 0
Disaster Subgroup                              0
Disaster Type                                  0
Disaster Subtype                               0
External IDs                                 111
Event Name                                   168
ISO                                            0
Country                                        0
Subregion                                      0
Region                                         0
Location                                      17
Origin                                       100
Associated Types                              47
OFDA Response                                  0
Appeal                                         0
Declaration                                    0
AID Contribution ('000 US$)                  162
Magnitude                                    164
Magnitude Scale                                0
Latitude                                     168
Longitude                                    168
River Basin                                  168
Start Year                                     0
Start Month                                   35
Start Day                                    167
End Year                                       0
End Month                                     66
End Day                                      166
Total Deaths                                 155
No. Injured                                  168
No. Affected                                  12
No. Homeless                                 168
Total Affected                                12
Reconstruction Costs ('000 US$)              168
Reconstruction Costs, Adjusted ('000 US$)    168
Insured Damage ('000 US$)                    168
Insured Damage, Adjusted ('000 US$)          168
Total Damage ('000 US$)                      157
Total Damage, Adjusted ('000 US$)            157
CPI                                            0
Admin Units                                   24
Entry Date                                     0
Last Update                                    0
dtype: int64

In [ ]:
df = df.dropna(axis='columns',how= 'all')
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,ISO,Country,...,End Day,Total Deaths,No. Affected,Total Affected,Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,1999-9388-DJI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,DJI,Djibouti,...,NaN,NaN,100000.0,100000.0,NaN,NaN,60.503579,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,1999-9388-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,SDN,Sudan,...,NaN,NaN,2000000.0,2000000.0,NaN,NaN,58.840648,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,1999-9388-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,SOM,Somalia,...,NaN,21.0,1200000.0,1200000.0,NaN,NaN,58.840648,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,2000-9309-MDG,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,MDG,Madagascar,...,NaN,NaN,231290.0,231290.0,NaN,NaN,58.840648,"[{""adm2_code"":154509,""adm2_name"":""Ambatondraza...",2008-01-03,2023-09-25
4,2001-9044-BFA,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,BFA,Burkina Faso,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":40286,""adm1_name"":""Plateau Centr...",2006-10-26,2023-09-25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 36 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DisNo.                             168 non-null    object
 1   Historic                           168 non-null    object
 2   Classification Key                 168 non-null    object
 3   Disaster Group                     168 non-null    object
 4   Disaster Subgroup                  168 non-null    object
 5   Disaster Type                      168 non-null    object
 6   Disaster Subtype                   168 non-null    object
 7   External IDs                       57 non-null     object
 8   ISO                                168 non-null    object
 9   Country                            168 non-null    object
 10  Subregion                          168 non-null    object
 11  Region                             168 non-null    object
 12  Location                           151 non-null    object
 13  Origin                             68 non-null     object
 14  Associated Types                   121 non-null    object
 15  OFDA Response                      168 non-null    object
 16  Appeal                             168 non-null    object
 17  Declaration                        168 non-null    object
 18  AID Contribution ('000 US$)        6 non-null      float64
 19  Magnitude                          4 non-null      float64
 20  Magnitude Scale                    168 non-null    object
 21  Start Year                         168 non-null    int64
 22  Start Month                        133 non-null    float64
 23  Start Day                          1 non-null      float64
 24  End Year                           168 non-null    int64
 25  End Month                          102 non-null    float64
 26  End Day                            2 non-null      float64
 27  Total Deaths                       13 non-null     float64
 28  No. Affected                       156 non-null    float64
 29  Total Affected                     156 non-null    float64
 30  Total Damage ('000 US$)            11 non-null     float64
 31  Total Damage, Adjusted ('000 US$)  11 non-null     float64
 32  CPI                                168 non-null    float64
 33  Admin Units                        144 non-null    object
 34  Entry Date                         168 non-null    datetime64[ns]
 35  Last Update                        168 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(12), int64(2), object(20)
memory usage: 47.4+ KB

In [ ]:
df.shape

(168, 36)

In [ ]:
df.describe()

,AID Contribution ('000 US$),Magnitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Affected,Total Affected,Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Entry Date,Last Update
count,6.000000,4.0,168.000000,133.000000,1.0,168.000000,102.000000,2.000000,13.000000,1.560000e+02,1.560000e+02,1.100000e+01,1.100000e+01,168.000000,168,168
mean,20172.000000,225.0,2011.327381,5.451128,1.0,2012.083333,7.117647,27.000000,1798.000000,2.655667e+06,2.655667e+06,5.032727e+05,5.869705e+05,77.019948,2013-06-21 22:51:25.714285824,2023-09-25 02:00:00
min,417.000000,0.0,2000.000000,1.000000,1.0,2000.000000,1.000000,23.000000,2.000000,1.200000e+04,1.200000e+04,4.400000e+04,5.432900e+04,58.840648,2005-09-05 00:00:00,2023-09-25 00:00:00
25%,704.000000,0.0,2005.000000,2.000000,1.0,2006.000000,3.000000,25.000000,9.000000,5.135000e+05,5.135000e+05,9.950000e+04,1.174685e+05,66.731058,2007-02-14 18:00:00,2023-09-25 00:00:00
50%,2178.000000,0.0,2011.000000,5.000000,1.0,2012.000000,7.000000,27.000000,58.000000,1.425000e+06,1.425000e+06,2.500000e+05,3.086850e+05,76.861595,2014-05-05 00:00:00,2023-09-25 00:00:00
75%,12138.250000,225.0,2017.000000,8.000000,1.0,2018.250000,11.000000,29.000000,120.000000,3.325000e+06,3.325000e+06,8.165000e+05,8.562340e+05,83.757255,2019-01-18 12:00:00,2023-09-25 00:00:00
max,100588.000000,900.0,2022.000000,12.000000,1.0,2023.000000,12.000000,31.000000,20000.000000,2.597281e+07,2.597281e+07,1.400000e+06,1.728639e+06,100.000000,2022-11-29 00:00:00,2023-09-26 00:00:00
std,39798.725271,450.0,6.976004,3.570642,NaN,7.025545,4.134602,5.656854,5510.078115,3.911632e+06,3.911632e+06,4.911607e+05,5.847477e+05,11.666006,NaN,NaN

In [ ]:
df.isnull().sum().sort_values(ascending=True)

DisNo.                                 0
Historic                               0
Classification Key                     0
Disaster Group                         0
Disaster Subgroup                      0
Disaster Type                          0
Disaster Subtype                       0
ISO                                    0
OFDA Response                          0
Country                                0
Subregion                              0
Region                                 0
Magnitude Scale                        0
Start Year                             0
Declaration                            0
Appeal                                 0
End Year                               0
Last Update                            0
Entry Date                             0
CPI                                    0
Total Affected                        12
No. Affected                          12
Location                              17
Admin Units                           24
Start Month                           35
Associated Types                      47
End Month                             66
Origin                               100
External IDs                         111
Total Deaths                         155
Total Damage, Adjusted ('000 US$)    157
Total Damage ('000 US$)              157
AID Contribution ('000 US$)          162
Magnitude                            164
End Day                              166
Start Day                            167
dtype: int64

In [ ]:
df = df.drop(columns=['Start Day','End Day', 'Magnitude', 'DisNo.', 'Historic'])
df.head()

,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,ISO,Country,Subregion,Region,...,End Month,Total Deaths,No. Affected,Total Affected,Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,DJI,Djibouti,Sub-Saharan Africa,Africa,...,NaN,NaN,100000.0,100000.0,NaN,NaN,60.503579,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,SDN,Sudan,Northern Africa,Africa,...,NaN,NaN,2000000.0,2000000.0,NaN,NaN,58.840648,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,SOM,Somalia,Sub-Saharan Africa,Africa,...,NaN,21.0,1200000.0,1200000.0,NaN,NaN,58.840648,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,MDG,Madagascar,Sub-Saharan Africa,Africa,...,NaN,NaN,231290.0,231290.0,NaN,NaN,58.840648,"[{""adm2_code"":154509,""adm2_name"":""Ambatondraza...",2008-01-03,2023-09-25
4,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,BFA,Burkina Faso,Sub-Saharan Africa,Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,60.503579,"[{""adm1_code"":40286,""adm1_name"":""Plateau Centr...",2006-10-26,2023-09-25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Classification Key                 168 non-null    object
 1   Disaster Group                     168 non-null    object
 2   Disaster Subgroup                  168 non-null    object
 3   Disaster Type                      168 non-null    object
 4   Disaster Subtype                   168 non-null    object
 5   External IDs                       57 non-null     object
 6   ISO                                168 non-null    object
 7   Country                            168 non-null    object
 8   Subregion                          168 non-null    object
 9   Region                             168 non-null    object
 10  Location                           151 non-null    object
 11  Origin                             68 non-null     object
 12  Associated Types                   121 non-null    object
 13  OFDA Response                      168 non-null    object
 14  Appeal                             168 non-null    object
 15  Declaration                        168 non-null    object
 16  AID Contribution ('000 US$)        6 non-null      float64
 17  Magnitude Scale                    168 non-null    object
 18  Start Year                         168 non-null    int64
 19  Start Month                        133 non-null    float64
 20  End Year                           168 non-null    int64
 21  End Month                          102 non-null    float64
 22  Total Deaths                       13 non-null     float64
 23  No. Affected                       156 non-null    float64
 24  Total Affected                     156 non-null    float64
 25  Total Damage ('000 US$)            11 non-null     float64
 26  Total Damage, Adjusted ('000 US$)  11 non-null     float64
 27  CPI                                168 non-null    float64
 28  Admin Units                        144 non-null    object
 29  Entry Date                         168 non-null    datetime64[ns]
 30  Last Update                        168 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(9), int64(2), object(18)
memory usage: 40.8+ KB

In [ ]:
cols_to_drop = [0,1,2,3,5,10,11,14,15,16,17,23,25,26,28,29,30]
df.drop(df.columns[cols_to_drop], axis=1, inplace= True)

In [ ]:
df.head()

,Disaster Subtype,ISO,Country,Subregion,Region,Associated Types,OFDA Response,Start Year,Start Month,End Year,End Month,Total Deaths,Total Affected,CPI
0,Drought,DJI,Djibouti,Sub-Saharan Africa,Africa,NaN,Yes,2001,6.0,2001,NaN,NaN,100000.0,60.503579
1,Drought,SDN,Sudan,Northern Africa,Africa,Food shortage|Water shortage,No,2000,1.0,2001,NaN,NaN,2000000.0,58.840648
2,Drought,SOM,Somalia,Sub-Saharan Africa,Africa,Food shortage,No,2000,1.0,2001,NaN,21.0,1200000.0,58.840648
3,Drought,MDG,Madagascar,Sub-Saharan Africa,Africa,NaN,No,2000,6.0,2000,NaN,NaN,231290.0,58.840648
4,Drought,BFA,Burkina Faso,Sub-Saharan Africa,Africa,NaN,No,2001,4.0,2001,NaN,NaN,NaN,60.503579

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster Subtype  168 non-null    object
 1   ISO               168 non-null    object
 2   Country           168 non-null    object
 3   Subregion         168 non-null    object
 4   Region            168 non-null    object
 5   Associated Types  121 non-null    object
 6   OFDA Response     168 non-null    object
 7   Start Year        168 non-null    int64
 8   Start Month       133 non-null    float64
 9   End Year          168 non-null    int64
 10  End Month         102 non-null    float64
 11  Total Deaths      13 non-null     float64
 12  Total Affected    156 non-null    float64
 13  CPI               168 non-null    float64
dtypes: float64(5), int64(2), object(7)
memory usage: 18.5+ KB

In [ ]:
cols_to_fill = ['Start Month','End Month','Total Deaths','Total Affected']
for column_name in cols_to_fill:
  df.loc[df[column_name].isna(), column_name] = 0
df.head()

,Disaster Subtype,ISO,Country,Subregion,Region,Associated Types,OFDA Response,Start Year,Start Month,End Year,End Month,Total Deaths,Total Affected,CPI
0,Drought,DJI,Djibouti,Sub-Saharan Africa,Africa,NaN,Yes,2001,6.0,2001,0.0,0.0,100000.0,60.503579
1,Drought,SDN,Sudan,Northern Africa,Africa,Food shortage|Water shortage,No,2000,1.0,2001,0.0,0.0,2000000.0,58.840648
2,Drought,SOM,Somalia,Sub-Saharan Africa,Africa,Food shortage,No,2000,1.0,2001,0.0,21.0,1200000.0,58.840648
3,Drought,MDG,Madagascar,Sub-Saharan Africa,Africa,NaN,No,2000,6.0,2000,0.0,0.0,231290.0,58.840648
4,Drought,BFA,Burkina Faso,Sub-Saharan Africa,Africa,NaN,No,2001,4.0,2001,0.0,0.0,0.0,60.503579

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster Subtype  168 non-null    object
 1   ISO               168 non-null    object
 2   Country           168 non-null    object
 3   Subregion         168 non-null    object
 4   Region            168 non-null    object
 5   Associated Types  121 non-null    object
 6   OFDA Response     168 non-null    object
 7   Start Year        168 non-null    int64
 8   Start Month       168 non-null    float64
 9   End Year          168 non-null    int64
 10  End Month         168 non-null    float64
 11  Total Deaths      168 non-null    float64
 12  Total Affected    168 non-null    float64
 13  CPI               168 non-null    float64
dtypes: float64(5), int64(2), object(7)
memory usage: 18.5+ KB

In [ ]:
columns_to_fill = ['Associated Types']
for column_name in columns_to_fill:
  df.loc[df[column_name].isna(), column_name] = 'Unspicified'
df.head()

,Disaster Subtype,ISO,Country,Subregion,Region,Associated Types,OFDA Response,Start Year,Start Month,End Year,End Month,Total Deaths,Total Affected,CPI
0,Drought,DJI,Djibouti,Sub-Saharan Africa,Africa,Unspicified,Yes,2001,6.0,2001,0.0,0.0,100000.0,60.503579
1,Drought,SDN,Sudan,Northern Africa,Africa,Food shortage|Water shortage,No,2000,1.0,2001,0.0,0.0,2000000.0,58.840648
2,Drought,SOM,Somalia,Sub-Saharan Africa,Africa,Food shortage,No,2000,1.0,2001,0.0,21.0,1200000.0,58.840648
3,Drought,MDG,Madagascar,Sub-Saharan Africa,Africa,Unspicified,No,2000,6.0,2000,0.0,0.0,231290.0,58.840648
4,Drought,BFA,Burkina Faso,Sub-Saharan Africa,Africa,Unspicified,No,2001,4.0,2001,0.0,0.0,0.0,60.503579

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster Subtype  168 non-null    object
 1   ISO               168 non-null    object
 2   Country           168 non-null    object
 3   Subregion         168 non-null    object
 4   Region            168 non-null    object
 5   Associated Types  168 non-null    object
 6   OFDA Response     168 non-null    object
 7   Start Year        168 non-null    int64
 8   Start Month       168 non-null    float64
 9   End Year          168 non-null    int64
 10  End Month         168 non-null    float64
 11  Total Deaths      168 non-null    float64
 12  Total Affected    168 non-null    float64
 13  CPI               168 non-null    float64
dtypes: float64(5), int64(2), object(7)
memory usage: 18.5+ KB

In [ ]:
type_dict = {
    'Start Year':'category',
    'Start Month':'category',
    'End Year':'category',
    'End Month':'category',
    'Total Deaths':'int64',
    'Total Affected':'int64'
}

for keys, vlaues in type_dict.items():
  df[keys] = df[keys].astype(vlaues)

df.head()

,Disaster Subtype,ISO,Country,Subregion,Region,Associated Types,OFDA Response,Start Year,Start Month,End Year,End Month,Total Deaths,Total Affected,CPI
0,Drought,DJI,Djibouti,Sub-Saharan Africa,Africa,Unspicified,Yes,2001,6.0,2001,0.0,0,100000,60.503579
1,Drought,SDN,Sudan,Northern Africa,Africa,Food shortage|Water shortage,No,2000,1.0,2001,0.0,0,2000000,58.840648
2,Drought,SOM,Somalia,Sub-Saharan Africa,Africa,Food shortage,No,2000,1.0,2001,0.0,21,1200000,58.840648
3,Drought,MDG,Madagascar,Sub-Saharan Africa,Africa,Unspicified,No,2000,6.0,2000,0.0,0,231290,58.840648
4,Drought,BFA,Burkina Faso,Sub-Saharan Africa,Africa,Unspicified,No,2001,4.0,2001,0.0,0,0,60.503579

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster Subtype  168 non-null    object
 1   ISO               168 non-null    object
 2   Country           168 non-null    object
 3   Subregion         168 non-null    object
 4   Region            168 non-null    object
 5   Associated Types  168 non-null    object
 6   OFDA Response     168 non-null    object
 7   Start Year        168 non-null    category
 8   Start Month       168 non-null    category
 9   End Year          168 non-null    category
 10  End Month         168 non-null    category
 11  Total Deaths      168 non-null    int64
 12  Total Affected    168 non-null    int64
 13  CPI               168 non-null    float64
dtypes: category(4), float64(1), int64(2), object(7)
memory usage: 16.7+ KB

In [ ]:
df

,Disaster Subtype,ISO,Country,Subregion,Region,Associated Types,OFDA Response,Start Year,Start Month,End Year,End Month,Total Deaths,Total Affected,CPI
0,Drought,DJI,Djibouti,Sub-Saharan Africa,Africa,Unspicified,Yes,2001,6.0,2001,0.0,0,100000,60.503579
1,Drought,SDN,Sudan,Northern Africa,Africa,Food shortage|Water shortage,No,2000,1.0,2001,0.0,0,2000000,58.840648
2,Drought,SOM,Somalia,Sub-Saharan Africa,Africa,Food shortage,No,2000,1.0,2001,0.0,21,1200000,58.840648
3,Drought,MDG,Madagascar,Sub-Saharan Africa,Africa,Unspicified,No,2000,6.0,2000,0.0,0,231290,58.840648
4,Drought,BFA,Burkina Faso,Sub-Saharan Africa,Africa,Unspicified,No,2001,4.0,2001,0.0,0,0,60.503579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,Drought,COD,Democratic Republic of the Congo,Sub-Saharan Africa,Africa,Unspicified,No,2022,0.0,2022,11.0,0,25972806,100.000000
164,Drought,MWI,Malawi,Sub-Saharan Africa,Africa,Unspicified,No,2022,0.0,2022,11.0,0,2678193,100.000000
165,Drought,MLI,Mali,Sub-Saharan Africa,Africa,Unspicified,No,2022,0.0,2022,11.0,0,1735753,100.000000
166,Drought,NGA,Nigeria,Sub-Saharan Africa,Africa,Unspicified,No,2022,0.0,2022,11.0,0,19110398,100.000000
167,Drought,SDN,Sudan,Northern Africa,Africa,Unspicified,No,2022,0.0,2022,11.0,0,11839300,100.000000

In [ ]:
df.to_csv('Emdat Clean.csv', index=False)

In [ ]:
from google.colab import files
files.download('Emdat Clean.csv')